language: node_js
dist: trusty
sudo: required

node_js:
  - "5"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  matrix:
    - MODULE=ng2-alfresco-core
    - MODULE=ng2-alfresco-datatable
    - MODULE=ng2-alfresco-documentlist
    - MODULE=ng2-alfresco-login
    - MODULE=ng2-alfresco-search
    - MODULE=ng2-alfresco-upload
    - MODULE=ng2-alfresco-viewer

before_script:
  - cd ng2-components/$MODULE; npm version patch; sed -i "s/0\\.0\\.0-PLACEHOLDER/^0.1.0/g" package.json; npm install; npm link
  ng2-alfresco-core; npm run travis
  - ls -ltrh ./node_modules/
script: npm run test
# Send coverage data to Coveralls
after_success:
  - "cat ./coverage/report/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose"